version: '3.4'

services:
  todolist_db:
    image: postgres:14.3
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=todolistappuser
      - POSTGRES_PASSWORD=todolistapppwd
      - POSTGRES_DB=todolistdb
    volumes:
      - todolistdbvolume:/var/lib/postgresql/data
    networks:
      - globalnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 25s
      retries: 5

  todolistapp:
    image: ${DOCKER_REGISTRY-}todolistapp
    build:
      context: .
      dockerfile: TodoListApp/Dockerfile
    depends_on:
      todolist_db:
        condition: service_healthy
    ports:
      - "4500:80"
    networks:
      - globalnetwork
    environment:
      - Conn_Str=Host=todolist_db;Port=5432;Database=todolistdb;Username=todolistappuser;Password=todolistapppwd

networks:
  globalnetwork:
    name: globalnetwork
volumes:
  todolistdbvolume:
